---
version: "3.0"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--certificatesresolvers.cloudflare.acme.email=${CF_API_EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - "./traefik/acme.json:/acme.json"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/middleware.yml:/etc/traefik/middleware.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - mediaserver
    env_file:
      - .env

networks:
  mediaserver:
    name: mediaserver
    external: true
